
spring:
  mail:
    host: smtp.mailtrap.io
    port: 25
    username: 4cd81fdec151b1
    password: e3e46c5a4f8988
    protocol: smtp
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/spring-reddit"
    username: joseph
    password: password

server:
  port: 8181
jwt:
  secret: "hvq0ouhHTBkkCPPrdEFSz0nj618j3EsNliuedM3x9szTc53QhCKT98JhXfLGwmc0oE8CV3j9ajRwUlBOrGQmc0oE8CV3j9ajRwUlBOrGQ"
  expiration:
      time: 86400000