spring:
  datasource:
   driver-class-name: org.h2.Driver
   url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false
   username: sa
   password:
  jpa:
   properties:
     hibernate.dialect: org.hibernate.dialect.H2Dialect